controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_controller_1:
      type: diff_drive_controller/DiffDriveController
    
    diff_controller_2:
      type: diff_drive_controller/DiffDriveController
    
    diff_controller_3:
      type: diff_drive_controller/DiffDriveController

diff_controller_1:
  ros__parameters:
    publish_rate: 50.0
    left_wheel_names: ['left_1_wheel_joint']
    right_wheel_names: ['right_1_wheel_joint']
    wheels_per_side: 1
    wheel_separation: 0.60745
    wheel_radius: 0.1
    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: true
    use_stampded_vel: false

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 3.0
    linear.x.min_velocity: -3.0
    linear.x.max_acceleration: 0.0
    linear.x.min_acceleration: 0.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 20.0
    angular.z.min_velocity: -20.0
    angular.z.max_acceleration: 0.0
    angular.z.min_acceleration: 0.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

diff_controller_2:
  ros__parameters:
    publish_rate: 50.0
    left_wheel_names: ['left_2_wheel_joint']
    right_wheel_names: ['right_2_wheel_joint']
    wheels_per_side: 1
    wheel_separation: 0.60745
    wheel_radius: 0.1
    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: true
    use_stampded_vel: false

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 3.0
    linear.x.min_velocity: -3.0
    linear.x.max_acceleration: 0.0
    linear.x.min_acceleration: 0.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 20.0
    angular.z.min_velocity: -20.0
    angular.z.max_acceleration: 0.0
    angular.z.min_acceleration: 0.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

diff_controller_3:
  ros__parameters:
    publish_rate: 50.0
    left_wheel_names: ['left_3_wheel_joint']
    right_wheel_names: ['right_3_wheel_joint']
    wheels_per_side: 1
    wheel_separation: 0.60745
    wheel_radius: 0.1
    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: true
    use_stampded_vel: false

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 3.0
    linear.x.min_velocity: -3.0
    linear.x.max_acceleration: 0.0
    linear.x.min_acceleration: 0.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 20.0
    angular.z.min_velocity: -20.0
    angular.z.max_acceleration: 0.0
    angular.z.min_acceleration: 0.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0